config/routes.rb
Rails.application.routes.draw do
  resources :blogs  do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "blogs#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
belongs_to :user
has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comment, optional: true
  belongs_to :blog
  belongs_to :user

  has_many :comments, dependent: :destroy

  validate :only_author_reply

  def only_author_reply
  if comment_id.present?
  errors.add(:base, "You are not authorized to do this action.") if user_id != blog.user_id
  end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :info, :error, :warning
	protected
     def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
     end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create edit update new destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(user: current_user))

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params.merge(user: current_user))
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :descreption)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_commentable, only: :create
before_action :authenticate_user!, only: %i[ create new ]

    def new
      @comment = Comment.new
    end

    def create

      comment = @commentable.comments.build(comment_params.merge(user: current_user))
      if params[:comment_id]
        comment.blog= @commentable.blog if params[:comment_id]
        @blog = @commentable.blog
      else
        @blog = @commentable
      end

      if comment.save
        flash[:success] = "successfully save"
        redirect_to @blog
      else
        flash[:error] = comment.errors.full_messages
        @blog = @blog
        render :template => "blogs/show"
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
    	
      if params[:comment_id]
        @commentable = Comment.find_by_id(params[:comment_id])
      elsif params[:blog_id]
        @commentable = Blog.find_by_id(params[:blog_id])
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :descreption %>
    <%= form.text_area :descreption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Descreption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.descreption %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
<p><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></p>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.descreption %>
</p>

<ul>
<%= render partial: 'comments/form' %>
</ul>

<ul>
<h1>Comments:-</h1>
<%= render partial: 'comments/comment', collection: @blog.comments.where(comment_id:nil) %>
</ul>
<% if user_signed_in? %>
  <% if current_user.id == @blog.user_id %>
    <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <% end %>
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %><% if current_user.present? %> -

  <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
      <% end %>
      <% end %>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/_form.html.erb
<% if current_user.present? %>
<li>Add a public comment</li>

<%= form_with(model: @comment, url: comments_path, local: true) do |form| %>
 <div class="field">
   <%= form.label :body %>
   <%= form.text_area :body, name: "comment[body]" %>
 </div>
  <%= form.hidden_field :blog_id, value: params[:id] %>

 <div class="actions">
   <%= form.submit %>
 </div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav">
      <%= link_to 'Blogs', blogs_path %>
      <% if user_signed_in? %>
        <%= current_user.first_name %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Register", new_user_registration_path %>
        <%= link_to('Login', new_user_session_path) %>  
      <% end %>
    </div>
    <% flash.each do |msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>